name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
    - "jni/**"
    - ".github/workflows/c-cpp.yml"
  pull_request:
    branches: [ "main" ]

jobs:
- build:
- runs-on: ubuntu-latest
- steps:
- name Run NDK
- uses: actions/checkout@v3
- uses: nttld/setup-ndk@v1
- with:
      ndk-version: r25c
  - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

