name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bash configure 
      run: bash configure && make && sudo make install  
    - name autoreconf
      run: autoreconf -i
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
