usename: C/C++ CI

on:
  push:
    branches: [ "main" ]

    paths:
    - "jni/**"
    - ".github/workflows/c-cpp.yml"
  pull_request:
    branches: [ "main" ]

jobs:
- build:
- name: Build su binary
- runs-on: ubuntu-latest
- name: Check out
- uses: actions/checkout@v4      
- name: Setup environment
- uses: ./.github/actions/setup
- name: Setup Android NDK
  uses: nttld/setup-ndk@v1.4.2
    - name: Build release
     run: ./build.py -vr all

    - name: Upload build artifact
     uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
